// <auto-generated />
using System;
using Filmsitesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filmsitesi.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20250416121440_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Filmsitesi.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filmad")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmÖzet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vizyontarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Filmler");
                });
#pragma warning restore 612, 618
        }
    }
}
